#############################################################################
# Makefile for building: Project2
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Mar 15 17:19:09 2013
# Project:  Project2/Project2.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Project2/Project2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -fopenmp -O2 -fopenmp -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -IProject2 -IProject2 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -fopenmp 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Project2/main.cpp \
		Project2/atom.cpp \
		Project2/cell.cpp \
		Project2/cellcontainer.cpp \
		Project2/cellsolver.cpp \
		Project2/normal.cpp \
		Project2/test.cpp \
		Project2/makematrix.cpp \
		Project2/simulation.cpp 
OBJECTS       = main.o \
		atom.o \
		cell.o \
		cellcontainer.o \
		cellsolver.o \
		normal.o \
		test.o \
		makematrix.o \
		simulation.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Project2/Project2.pro
QMAKE_TARGET  = Project2
DESTDIR       = 
TARGET        = Project2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project2/Project2.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Project2/Project2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Project2/Project2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Project21.0.0 || $(MKDIR) .tmp/Project21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Project21.0.0/ && (cd `dirname .tmp/Project21.0.0` && $(TAR) Project21.0.0.tar Project21.0.0 && $(COMPRESS) Project21.0.0.tar) && $(MOVE) `dirname .tmp/Project21.0.0`/Project21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Project21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: Project2/main.cpp Project2/atom.h \
		Project2/normal.hpp \
		Project2/cellsolver.h \
		Project2/cellcontainer.h \
		Project2/cell.h \
		Project2/test.h \
		Project2/makematrix.h \
		Project2/simulation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Project2/main.cpp

atom.o: Project2/atom.cpp Project2/atom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o atom.o Project2/atom.cpp

cell.o: Project2/cell.cpp Project2/cell.h \
		Project2/atom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o Project2/cell.cpp

cellcontainer.o: Project2/cellcontainer.cpp Project2/cellcontainer.h \
		Project2/cell.h \
		Project2/atom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cellcontainer.o Project2/cellcontainer.cpp

cellsolver.o: Project2/cellsolver.cpp Project2/cellsolver.h \
		Project2/cellcontainer.h \
		Project2/cell.h \
		Project2/atom.h \
		Project2/normal.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cellsolver.o Project2/cellsolver.cpp

normal.o: Project2/normal.cpp Project2/normal.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o normal.o Project2/normal.cpp

test.o: Project2/test.cpp Project2/test.h \
		Project2/cellsolver.h \
		Project2/cellcontainer.h \
		Project2/cell.h \
		Project2/atom.h \
		Project2/normal.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o Project2/test.cpp

makematrix.o: Project2/makematrix.cpp Project2/makematrix.h \
		Project2/cellsolver.h \
		Project2/cellcontainer.h \
		Project2/cell.h \
		Project2/atom.h \
		Project2/normal.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o makematrix.o Project2/makematrix.cpp

simulation.o: Project2/simulation.cpp Project2/simulation.h \
		Project2/makematrix.h \
		Project2/cellsolver.h \
		Project2/cellcontainer.h \
		Project2/cell.h \
		Project2/atom.h \
		Project2/normal.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulation.o Project2/simulation.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

